BC: ['bc/*', 'break/*']
feature: ['feature/*', 'feat/*']
bugfix: ['fix/*', 'bugfix/*']
refactoring: refactor/*
documentation: ['docs/*', 'documentation/*']
maintenance: ['maintenance/*', 'chore/*']
dependencies: ['dependencies/*']
